Config = {}

Config.RestrictedChannels = {
    [1] = { -- POLICE
        police = true,
        policeacademy = true,
        bcso = true,
        sahp = true,
        ambulance = true,
        prison = true,
        ranger = true,
        firefighter = true,
        cid = true,
    },
    [2] = { -- AMBULANCE
        police = true,
        policeacademy = true,
        bcso = true,
        sahp = true,
        ambulance = true,
        prison = true,
        ranger = true,
        firefighter = true,
        cid = true,
    },
    [3] = { -- DOC
        police = true,
        policeacademy = true,
        bcso = true,
        sahp = true,
        ambulance = true,
        prison = true,
        firefighter = true,
        cid = true,
    },
    [4] = { -- RANGERS
        police = true,
        policeacademy = true,
        bcso = true,
        sahp = true,
        ambulance = true,
        ranger = true,
        firefighter = true,
        cid = true,
    },
    [5] = { -- LEGAL
        police = true,
        policeacademy = true,
        bcso = true,
        sahp = true,
        ambulance = true,
        prison = true,
        ranger = true,
        judge = true,
        firefighter = true,
        cid = true,
    },
    [6] = { -- FIRE
        police = true,
        policeacademy = true,
        bcso = true,
        sahp = true,
        ambulance = true,
        prison = true,
        ranger = true,
        firefighter = true,
        cid = true,
    },
    [7] = {
        police = true,
        bcso = true,
        sahp = true,
        ambulance = true,
        prison = true,
        cid = true,
    },
    [8] = {
        police = true,
        bcso = true,
        sahp = true,
        ambulance = true,
        prison = true,
        cid = true,
    },
    [9] = {
        police = true,
        bcso = true,
        sahp = true,
        ambulance = true,
        prison = true,
        cid = true,
    },
    [10] = {
        completeauto = true,
        mechanic = true,
        hayes = true,
        lscustoms = true,
    }
}

Config.MaxFrequency = 500